10/18/2024 02:02:51 - INFO - __main__ - Distributed environment: MULTI_CPU  Backend: gloo
Num processes: 2
Process index: 1
Local process index: 1
Device: cpu:0

Mixed precision type: bf16

10/18/2024 02:02:51 - INFO - __main__ - Distributed environment: MULTI_CPU  Backend: gloo
Num processes: 2
Process index: 0
Local process index: 0
Device: cpu:0

Mixed precision type: bf16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards: 100%|██████████| 2/2 [00:00<00:00, 2097.15it/s]
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards: 100%|██████████| 2/2 [00:00<00:00, 3526.11it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.03s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.04s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.88s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.91s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.89s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.92s/it]
{'use_learned_positional_embeddings'} was not found in config. Values will be initialized to default values.
Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]Loading pipeline components...:   0%|          | 0/5 [00:00<?, ?it/s]Loading pipeline components...: 100%|██████████| 5/5 [00:00<00:00, 34.78it/s]Loading pipeline components...: 100%|██████████| 5/5 [00:00<00:00, 34.73it/s]
Loaded tokenizer as T5Tokenizer from `tokenizer` subfolder of THUDM/CogVideoX-2b.
Loading pipeline components...:  20%|██        | 1/5 [00:00<00:00,  7.14it/s]Loaded scheduler as CogVideoXDDIMScheduler from `scheduler` subfolder of THUDM/CogVideoX-2b.
Loading pipeline components...: 100%|██████████| 5/5 [00:00<00:00, 35.09it/s]
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: lyricmayday (yangluo). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.3
wandb: Run data is saved locally in /home/svu/e0833524/CogVideo/finetune/wandb/run-20241018_020318-05nsmuob
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run breezy-breeze-1
wandb: ⭐️ View project at https://wandb.ai/yangluo/cogvideox-lora
wandb: 🚀 View run at https://wandb.ai/yangluo/cogvideox-lora/runs/05nsmuob
10/18/2024 02:03:21 - INFO - __main__ - ***** Running training *****
10/18/2024 02:03:21 - INFO - __main__ -   Num trainable parameters = 1700926302
10/18/2024 02:03:21 - INFO - __main__ -   Num examples = 69
10/18/2024 02:03:21 - INFO - __main__ -   Num batches each epoch = 35
10/18/2024 02:03:21 - INFO - __main__ -   Num epochs = 30
10/18/2024 02:03:21 - INFO - __main__ -   Instantaneous batch size per device = 1
10/18/2024 02:03:21 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 2
10/18/2024 02:03:21 - INFO - __main__ -   Gradient accumulation steps = 1
10/18/2024 02:03:21 - INFO - __main__ -   Total optimization steps = 1050
Steps:   0%|          | 0/1050 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1320, in <module>
    main(args)
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1091, in main
    generated_latents_teacher = pipe_teacher(prompt=prompt, guidance_scale=6, use_dynamic_cfg=True, num_inference_steps=50).generated_latents
NameError: name 'prompt' is not defined. Did you mean: 'prompts'?
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1320, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1091, in main
[rank1]:     generated_latents_teacher = pipe_teacher(prompt=prompt, guidance_scale=6, use_dynamic_cfg=True, num_inference_steps=50).generated_latents
[rank1]: NameError: name 'prompt' is not defined. Did you mean: 'prompts'?
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1320, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1091, in main
[rank0]:     generated_latents_teacher = pipe_teacher(prompt=prompt, guidance_scale=6, use_dynamic_cfg=True, num_inference_steps=50).generated_latents
[rank0]: NameError: name 'prompt' is not defined. Did you mean: 'prompts'?
W1018 02:03:22.774000 22807322256512 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 216365 closing signal SIGTERM
E1018 02:03:22.887000 22807322256512 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 216366) of binary: /hpctmp/e0833524/virtualenvs/cogvideo/bin/python
Traceback (most recent call last):
  File "/hpctmp/e0833524/virtualenvs/cogvideo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
KD.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-18_02:03:22
  host      : hopper-06.cm.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 216366)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
