10/18/2024 01:06:23 - INFO - __main__ - Distributed environment: MULTI_CPU  Backend: gloo
Num processes: 2
Process index: 0
Local process index: 0
Device: cpu:0

Mixed precision type: bf16

10/18/2024 01:06:23 - INFO - __main__ - Distributed environment: MULTI_CPU  Backend: gloo
Num processes: 2
Process index: 1
Local process index: 1
Device: cpu:0

Mixed precision type: bf16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]Downloading shards:  50%|█████     | 1/2 [07:06<07:06, 426.83s/it]Downloading shards:  50%|█████     | 1/2 [07:06<07:06, 426.87s/it]Downloading shards: 100%|██████████| 2/2 [13:34<00:00, 403.61s/it]Downloading shards: 100%|██████████| 2/2 [13:34<00:00, 407.09s/it]
Downloading shards: 100%|██████████| 2/2 [13:34<00:00, 403.63s/it]Downloading shards: 100%|██████████| 2/2 [13:34<00:00, 407.12s/it]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:12<00:12, 12.62s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:12<00:12, 12.73s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.78s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.90s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.82s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.95s/it]
{'use_learned_positional_embeddings'} was not found in config. Values will be initialized to default values.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1319, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 856, in main
[rank0]:     discriminator = MultiLayerDiscriminator(latent_dim=768, num_discriminators=30)
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 520, in __init__
[rank0]:     self.discriminators = nn.ModuleList([LatentDiscriminatorHead(latent_dim) for _ in range(num_discriminators)])
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 520, in <listcomp>
[rank0]:     self.discriminators = nn.ModuleList([LatentDiscriminatorHead(latent_dim) for _ in range(num_discriminators)])
[rank0]: NameError: name 'LatentDiscriminatorHead' is not defined. Did you mean: 'LatentDiscriminator'?
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1319, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 856, in main
[rank1]:     discriminator = MultiLayerDiscriminator(latent_dim=768, num_discriminators=30)
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 520, in __init__
[rank1]:     self.discriminators = nn.ModuleList([LatentDiscriminatorHead(latent_dim) for _ in range(num_discriminators)])
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 520, in <listcomp>
[rank1]:     self.discriminators = nn.ModuleList([LatentDiscriminatorHead(latent_dim) for _ in range(num_discriminators)])
[rank1]: NameError: name 'LatentDiscriminatorHead' is not defined. Did you mean: 'LatentDiscriminator'?
E1018 01:26:07.360000 22722244949120 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 2026740) of binary: /hpctmp/e0833524/virtualenvs/cogvideo/bin/python
Traceback (most recent call last):
  File "/hpctmp/e0833524/virtualenvs/cogvideo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
KD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-18_01:26:07
  host      : hopper-04.cm.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2026741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-18_01:26:07
  host      : hopper-04.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2026740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
